{% set version = "1.10.2" %}

package:
  name: sphinx-autodoc-typehints
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sphinx-autodoc-typehints/sphinx-autodoc-typehints-{{ version }}.tar.gz
  sha256: 94b07777acfec584692fa64ae8d423b709a76c2a02de8a337a1f19378b8820ed

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3
    - pip
    - sphinx >=1.4
    - setuptools_scm
  run:
    - python >=3
    - sphinx >=1.4

test:
  imports:
    - sphinx_autodoc_typehints

about:
  home: https://github.com/agronholm/sphinx-autodoc-typehints
  license: MIT
  license_file: LICENSE
  summary: 'Type hints (PEP 484) support for the Sphinx autodoc extension'
  license_family: MIT

extra:
  recipe-maintainers:
    - kwilcox
