{% set name = "sphinx-autodoc-typehints" %}
{% set version = "1.21.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinx_autodoc_typehints-{{ version }}.tar.gz
  sha256: 68e7136403ca67359d7beaab4d358cea518623abe749cc4e0639609aebf2f5c7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling >=1.12.2
    - hatch-vcs >=0.3
    - pip
  run:
    - python >=3.7
    - sphinx >=5.3

test:
  imports:
    - sphinx_autodoc_typehints
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/sphinx-autodoc-typehints/
  summary: Type hints (PEP 484) support for the Sphinx autodoc extension
  dev_url: https://github.com/tox-dev/sphinx-autodoc-typehints
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
