{% set version = "1.18.1" %}

package:
  name: sphinx-autodoc-typehints
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sphinx-autodoc-typehints/sphinx_autodoc_typehints-{{ version }}.tar.gz
  sha256: 07631c5f0c6641e5ba27143494aefc657e029bed3982138d659250e617f6f929

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools >=36.2.7
    - setuptools_scm >=1.7.0
  run:
    - python >=3.7
    - sphinx >=4.5

test:
  imports:
    - sphinx_autodoc_typehints
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tox-dev/sphinx-autodoc-typehints
  license: MIT
  license_file: LICENSE
  summary: Type hints (PEP 484) support for the Sphinx autodoc extension
  license_family: MIT

extra:
  recipe-maintainers:
    - kwilcox
