{% set version = "1.20.0" %}

package:
  name: sphinx-autodoc-typehints
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sphinx-autodoc-typehints/sphinx_autodoc_typehints-{{ version }}.tar.gz
  sha256: 776a6439f1f602d4685f5046d00a90b38d8c075884ee81fe075260e92d152d9b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling >=1.10
    - hatch-vcs >=0.2
  run:
    - python >=3.7
    - sphinx >=5.3

test:
  imports:
    - sphinx_autodoc_typehints
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/sphinx-autodoc-typehints/
  summary: Type hints (PEP 484) support for the Sphinx autodoc extension
  license: MIT
  license_file: LICENSE
  license_family: MIT

extra:
  recipe-maintainers:
    - kwilcox
