travis:
  secure:
    BINSTAR_TOKEN: AmWc0zjVcF9tO/s4Suy76ABbzlupN9ww2us3qmxl6579Y9uxuZtAvAN/4kUWcb/6nCRsqIRRZ/khwr6v5l9/xBznVsd3Eh0OH7HqfYeXiY9qbjxkJ8mbXzVVRWqhTeM77X3uLKpocBv6oFAQMsHrF+nMgqg5vQt2/P/7o6Bkeg3kwMbMOYFh7jfiDzWyhIIl41nx6OF6TSbQXyKwZcbVREZ5KZFcIZiZa9eP6D6X8IgsRB7hgugnnKAIbdaJZ1ePxNooeUlD0gwUtGmtLMiXnxTtQHeyZOj8YMCzLzreiyq0Qj2XmDW2kREVbFdj5lfGDEoC7jWStdEPi85v6X4WZzpwsBfKkZCjekp/DyI+7iJlrBqzipJy/nqx6osQ69XxEp+X6kJRVEPTkIvo3A2CXWCXKvRsWmvd7BEDhTLmJPsINbqLG6aM2Zv1A0UcaCk1MlbtniY95gfXydfPrxn50ApDYMBoq7C1gWJRbQkMD+Ttv07oThGSrnPhhgLReHoyABcOt1K/ZcWUI/EfnlJEsgkhJuW73HbSAWSeq3h1VFUcYqJOflx/NxHJqT9XJJV8FBc9uuE6iNJbzrBL4Io2Y0XmLotFqqnTdehU/uNE01EWlpa+nCgkCdv09OKedNl1Ei7HGNnhk4nS9bcqQXRAVxxx4qD8+1tPA2nDLhU2rqg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
